--------------------------------------------------------------
 --  Copyright (c) 2012-2025 Anlogic Inc. --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	D:/FPGA/TD_project/eth_vision_system/al_ip/font_blue.vhd
 -- Date	:	2025 10 25
 -- TD version	:	6.2.168116
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY eagle_macro;
	USE eagle_macro.EAGLE_COMPONENTS.all;

ENTITY font_blue IS
PORT (
	doa		: OUT STD_LOGIC_VECTOR(23 DOWNTO 0);

	addra	: IN STD_LOGIC_VECTOR(11 DOWNTO 0);
	clka		: IN STD_LOGIC
	);
END font_blue;

ARCHITECTURE struct OF font_blue IS

	BEGIN
	inst : EG_LOGIC_BRAM
		GENERIC MAP (
			DATA_WIDTH_A	=> 24,
			ADDR_WIDTH_A	=> 12,
			DATA_DEPTH_A	=> 2500,
			DATA_WIDTH_B	=> 24,
			ADDR_WIDTH_B	=> 12,
			DATA_DEPTH_B	=> 2500,
			MODE			=> "SP",
			REGMODE_A	=> "NOREG",
			IMPLEMENT	=> "9K",
			DEBUGGABLE	=> "NO",
			PACKABLE		=> "NO",
			INIT_FILE	=> "../mif/blue.mif",
			FILL_ALL		=> "NONE"
		)
		PORT MAP (
			dia		=> (others=>'0'),
			dib		=> (others=>'0'),
			addra	=> addra,
			addrb	=> (others=>'0'),
			cea		=> '1',
			ceb		=> '0',
			clka		=> clka,
			clkb		=> '0',
			web		=> '0',
			rsta		=> '0',
			rstb		=> '0',
			doa		=> doa,
			dob		=> OPEN,
			ocea		=> '0',
			oceb		=> '0'
		);

END struct;
