/************************************************************\
 **  Copyright (c) 2012-2025 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	D:/FPGA/TD_project/eth_vision_system/al_ip/font_green.v
 ** Date	:	2025 10 25
 ** TD version	:	6.2.168116
************************************************************/

`timescale 1ns / 1ps

module font_green ( doa, addra, clka );

	output [23:0] doa;

	input  [11:0] addra;
	input  clka;



	EG_LOGIC_BRAM #( .DATA_WIDTH_A(24),
				.ADDR_WIDTH_A(12),
				.DATA_DEPTH_A(2500),
				.DATA_WIDTH_B(24),
				.ADDR_WIDTH_B(12),
				.DATA_DEPTH_B(2500),
				.MODE("SP"),
				.REGMODE_A("NOREG"),
				.IMPLEMENT("9K"),
				.DEBUGGABLE("NO"),
				.PACKABLE("NO"),
				.INIT_FILE("../mif/green.mif"),
				.FILL_ALL("NONE"))
			inst(
				.dia({24{1'b0}}),
				.dib({24{1'b0}}),
				.addra(addra),
				.addrb({12{1'b0}}),
				.cea(1'b1),
				.ceb(1'b0),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(1'b0),
				.wea(1'b0),
				.web(1'b0),
				.bea(1'b0),
				.beb(1'b0),
				.rsta(1'b0),
				.rstb(1'b0),
				.doa(doa),
				.dob());


endmodule