/************************************************************\
 **  Copyright (c) 2012-2025 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	D:/FPGA/TD_project/eth_vision_system/al_ip/pic_data_ram.v
 ** Date	:	2025 10 22
 ** TD version	:	6.2.168116
************************************************************/

`timescale 1ns / 1ps

module pic_data_ram ( 
	dia, addra, cea, clka, wea,
	dob, addrb, ceb, clkb
);


	parameter DATA_WIDTH_A = 8; 
	parameter ADDR_WIDTH_A = 14;
	parameter DATA_DEPTH_A = 13000;
	parameter DATA_WIDTH_B = 16;
	parameter ADDR_WIDTH_B = 13;
	parameter DATA_DEPTH_B = 6500;
	parameter REGMODE_A    = "NOREG";
	parameter REGMODE_B    = "NOREG";
	parameter WRITEMODE_A  = "WRITETHROUGH";
	parameter WRITEMODE_B  = "WRITETHROUGH";

	output [DATA_WIDTH_B-1:0] dob;


	input  [DATA_WIDTH_A-1:0] dia;
	input  [ADDR_WIDTH_A-1:0] addra;
	input  [ADDR_WIDTH_B-1:0] addrb;
	input  [0:0] wea;
	input  cea;
	input  ceb;
	input  clka;
	input  clkb;



	EG_LOGIC_BRAM #( .DATA_WIDTH_A(DATA_WIDTH_A),
				.DATA_WIDTH_B(DATA_WIDTH_B),
				.ADDR_WIDTH_A(ADDR_WIDTH_A),
				.ADDR_WIDTH_B(ADDR_WIDTH_B),
				.DATA_DEPTH_A(DATA_DEPTH_A),
				.DATA_DEPTH_B(DATA_DEPTH_B),
				.BYTE_ENABLE(8),
				.BYTE_A(1),
				.BYTE_B(2),
				.MODE("PDPW"),
				.REGMODE_A(REGMODE_A),
				.REGMODE_B(REGMODE_B),
				.WRITEMODE_A(WRITEMODE_A),
				.WRITEMODE_B(WRITEMODE_B),
				.RESETMODE("SYNC"),
				.IMPLEMENT("9K"),
				.INIT_FILE("NONE"),
				.FILL_ALL("NONE"))
			inst(
				.dia(dia),
				.dib({16{1'b0}}),
				.addra(addra),
				.addrb(addrb),
				.cea(cea),
				.ceb(ceb),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(clkb),
				.wea(1'b0),
				.bea(wea),
				.web(1'b0),
				.beb(2'b00),
				.rsta(1'b0),
				.rstb(1'b0),
				.doa(),
				.dob(dob));


endmodule