--------------------------------------------------------------
 --  Copyright (c) 2012-2025 Anlogic Inc. --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	D:/FPGA/TD_project/eth_vision_system/al_ip/pic_data_ram.vhd
 -- Date	:	2025 10 22
 -- TD version	:	6.2.168116
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY eagle_macro;
	USE eagle_macro.EAGLE_COMPONENTS.all;

ENTITY pic_data_ram IS
PORT (
	dob	: OUT STD_LOGIC_VECTOR(15 DOWNTO 0);

	dia	: IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	addra	: IN STD_LOGIC_VECTOR(13 DOWNTO 0);
	wea	: IN STD_LOGIC_VECTOR (0 DOWNTO 0);
	cea	: IN STD_LOGIC;
	clka	: IN STD_LOGIC;
	addrb	: IN STD_LOGIC_VECTOR(12 DOWNTO 0);
	ceb	: IN STD_LOGIC;
	clkb	: IN STD_LOGIC
	);
END pic_data_ram;

ARCHITECTURE struct OF pic_data_ram IS

	BEGIN
	inst : EG_LOGIC_BRAM
		GENERIC MAP (
			DATA_WIDTH_A	=> 8,
			DATA_WIDTH_B	=> 16,
			ADDR_WIDTH_A	=> 14,
			ADDR_WIDTH_B	=> 13,
			DATA_DEPTH_A	=> 13000,
			DATA_DEPTH_B	=> 6500,
			BYTE_ENABLE	=> 8,
			BYTE_A	=> 1,
			BYTE_B	=> 2,
			MODE		=> "PDPW",
			REGMODE_A	=> "NOREG",
			REGMODE_B	=> "NOREG",
			WRITEMODE_A	=> "WRITETHROUGH",
			WRITEMODE_B	=> "WRITETHROUGH",
			RESETMODE	=> "SYNC",
			IMPLEMENT		=> "9K",
			INIT_FILE		=> "NONE",
			FILL_ALL		=> "NONE"
		)
		PORT MAP (
			dia	=> dia,
			dib	=> (others=>'0'),
			addra	=> addra,
			addrb	=> addrb,
			cea	=> cea,
			ceb	=> ceb,
			clka	=> clka,
			clkb	=> clkb,
			wea	=> '0',
			bea	=> wea,
			web	=> '0',
			beb	=> (others=>'0'),
			ocea	=> '0',
			oceb	=> '0',
			rsta	=> '0',
			rstb	=> '0',
			doa	=> OPEN,
			dob	=> dob
		);

END struct;
